### ISSUE TITLE
lil.eth - QVStrategy : Funds locked if no registered recipient or no recipientStatus >= reviewThreshold

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-09-Gitcoin-judging#207]
lil.eth

medium

# QVStrategy : Funds locked if no registered recipient or no recipientStatus >= reviewThreshold
Both RFP and Merkle strategies have an in-build `withdraw()` function that allow poolManagers to withdraw funds in case of problem/no recipient registration/no recipient acceptation.
However QVStrategy doesn't have one , so in case of no registration or no acceptation of a recipient before `registrationEndTime` is passed  , funds deposited on the strategy contract will be lock.

## Vulnerability Detail
As explained above, both RFP and Merkle strategies have withdraw() function : 

- DonationVotingMerkleDistributionBaseStrategy.sol : 
```solidity
    function withdraw(uint256 _amount) external onlyPoolManager(msg.sender) {
        //E must be one month after allocationEndTime
        if (block.timestamp <= allocationEndTime + 30 days) {
            revert INVALID();
        }
        IAllo.Pool memory pool = allo.getPool(poolId);
        if (_amount > poolAmount) { 
            revert INVALID();
        }
        poolAmount -= _amount;
        // Transfer the tokens to the 'msg.sender' (pool manager calling function)
        _transferAmount(pool.token, msg.sender, _amount);
    }
```

- RFPSimpleStrategy.sol : 
```solidity
    function withdraw(uint256 _amount) external onlyPoolManager(msg.sender) onlyInactivePool {
        // Decrement the pool amount
        poolAmount -= _amount;
        // Transfer the amount to the pool manager
        _transferAmount(allo.getPool(poolId).token, msg.sender, _amount);
    }
```
But QV strategy doesn't implement an in-built withdraw function, so the only process to distribute funds locked on a QV Strategy would be to have a recipient reviewed by `poolManager` more than `reviewThreshold` time before `registrationEndTime` :
```solidity
//E Add 1 Review for recipient(s) application(s) and set status of the corresponding recipient struct ONLY if it passes the threshold
    function reviewRecipients(address[] calldata _recipientIds, Status[] calldata _recipientStatuses) external virtual
        onlyPoolManager(msg.sender)  //E if hasRole(pools[_poolId].managerRole, _address) || _isPoolAdmin(_poolId, _address);
        onlyActiveRegistration
    {
        .....
        for (uint256 i; i < recipientLength;) {
            ....
            //E mapping(address => mapping(Status => uint256)) public reviewsByStatus; //E recipientId -> status -> count
            reviewsByStatus[recipientId][recipientStatus]++;

            //E check if it passed threshold of reviewing
            if (reviewsByStatus[recipientId][recipientStatus] >= reviewThreshold) { //E @question what if reviewThreshold change ? PoolManager has to resend this tx
                Recipient storage recipient = recipients[recipientId];
                recipient.recipientStatus = recipientStatus;
                emit RecipientStatusUpdated(recipientId, recipientStatus, address(0));
            }
           ...
        }
    }
```
And then have a poolManager calling `_distribute()` function using Allo.sol (this function can be called anytime after `allocationEndTime`)

**However if no recipient passes `reviewThreshold` or no recipient at all register for this strategy, funds will be locked on the strategy contract.**
(We could think about modifying timestamps using `updatePoolTimestamps()` but this function reverts `if block.timestamp > _registrationStartTime`)
**So once the process of registration is launch on a QV Strategy there is no other possibilities to unlock the funds than having a recipient registering and accepted before end of `registrationEndTime`, if one of these conditions failed, funds will be locked.**

I validate this problem with sponsor who answered "Ah you're right ! We should have a withdraw function. Good catch on that"

## Impact

If between `registrationStartTime` and `registrationEndTime` there is no accepted registration , funds will be locked on this contract with no way to unlock them.

## Code Snippet

https://github.com/allo-protocol/allo-v2/blob/main/contracts/strategies/qv-base/QVBaseStrategy.sol#L369

## Tool used

Manual Review

## Recommendation

Add a `withdraw()` function for `poolManagers` on the QV Strategy in the same model as there is one in RFP Strategy

NB : it is also true if valid allocator forgets to vote as amount sent is calculated in `_getPayout()` function only if `totalRecipientVotes != 0` and even if this case would be strange it would necessite a `withdraw()` function

Duplicate of #446

**Comment by nevillehuang** [comment]
Escalate

While there are multiple different reasons that locking of funds can occur, the root cause is the same, that is funds are stuck in the QVBaseStrategy contract and should implement a withdraw function. So should be dupe with #446

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> While there are multiple different reasons that locking of funds can occur, the root cause is the same, that is funds are stuck in the QVBaseStrategy contract and should implement a withdraw function. So should be dupe with #446 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by jkoppel** [comment]
Escalate.

This says that, if they money has not been allocated, then the money has not been allocated. The solution is to allocate the money, which the owner can always do. It looks like intended behavior to me, or at best a low.

#446 says that, even if they have allocated the money, funds can get stuck.

To put this another way: #446 both says that stuck funds cannot be withdrawn, and provides a mechanism by which funds can get stuck.

This one just says that stuck funds cannot be withdrawn, and then argues that not-yet-allocated funds should be considered stuck, which I don't find reasonable.

I think this should be a low. It contains a strict subset of the information in #446, and should at best be marked a duplicate of it.

**Comment by sherlock-admin2** [comment]
> Escalate.
> 
> This says that, if they money has not been allocated, then the money has not been allocated. The solution is to allocate the money, which the owner can always do. It looks like intended behavior to me, or at best a low.
> 
> #446 says that, even if they have allocated the money, funds can get stuck.
> 
> To put this another way: #446 both says that stuck funds cannot be withdrawn, and provides a mechanism by which funds can get stuck.
> 
> This one just says that stuck funds cannot be withdrawn, and then argues that not-yet-allocated funds should be considered stuck, which I don't find reasonable.
> 
> I think this should be a low. It contains a strict subset of the information in #446, and should at best be marked a duplicate of it.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xllill** [comment]
Escalations are false, @jkoppel this finding is not saying that "if money has not been allocated, then the money has not been allocated", but that once the process of registration is launch on a `QV Strategy` there is no other possibilities to unlock/distribute the funds than 

1. Having a recipient registering 
2. Having an accepted recipient before the end of `registrationEndTime`

As said above,if one of these conditions fail (because there is no recipient or there is no accepted recipient), then **funds will be locked forever on the strategy contract** (have a look at the bold part of the finding please). 
Moreover @jkoppel (read the findings once again please) is again wrong when saying owner can always allocate because `QVBaseStrategy.sol#_qv_allocate()` has the `onlyActiveAllocation` modifier and owner cannot modify timestamps using `updatePoolTimestamps()` because this function reverts if `block.timestamp > _registrationStartTime` as said in the finding.

@nevillehuang As the lead judge said correctly "the root cause of fund locking in this submission is different" because in #446 , the main impact is about the funds that will be locked after distribution started due to the fact that `Allo.sol#fundPool()` can be called by anyone at anytime as you can see on the impact section of #446 : "If some funds are added **after** the distribution is started, the added funds may be locked." and only in this particular case.
Mine is totally different because it's not talking about the same funds, mine is talking about funds added during the whole process, **mostly during the strategy creation funds** and of course funds added after when #446 is talking only about the funds added after distribution started (as you can see on the titles of the 446 and dupplicates : "late arriving funds","after some user already received funds" or "If someone fund a pool when the fund is partially/fully distributed") which is totally different.

=> So to conclude it should be a valid medium with a totally different root cause than #446 because we are not talking about the same funds, we are talking about a different part of the process and also about a different root cause.

**Comment by nevillehuang** [comment]
Root cause is the same, you cannot withdraw any funds funded into the contract due to a lack of a withdraw option. Whether it being
- funding after partial/full distribution
- or no recipient threshold pass during voting process

In fact i would argue the reason you described has a very low chance of occurring as it is a very specific scenario. Additionally, @jkoppel is right, pool manager can always adjust `_registrationTime` accordingly so the statement that `it reverts if block.timestamp > registrationStartTime` is incorrect. This issue should be low severity.

**Comment by jkoppel** [comment]
>  because this function reverts if block.timestamp > _registrationStartTime as said in the finding.

You misread this. You're thinking that it reverts if `block.timestamp > registrationStartTime`, i.e.: once registration has started, then you can't change the times at all. But this is not the code.  It uses the parameter `_registrationStartTime`, not the contract storage variable `registrationStartTime`. You can always update the pool timestamps to create a new registration period in the future.

**Comment by neeksec** [comment]
Agree with Escalation this is a duplicate of #446.

After re-reviewing all the fund locking senarios in Watsons submissions(this one and #446, #431, #537 etc.). I think all of them are sub-cases of **funds locking becasue funds are not fully distributed** and the fix for these cases is to withdraw the non-distributed funds. So they should be duplicated.

**Comment by 0xllill** [comment]
kind of agree with that : "sub-cases of funds locking because funds are not fully distributed and the fix for these cases is to withdraw the non-distributed funds." so agree with lead judge

**Comment by MLON33** [comment]
https://github.com/allo-protocol/allo-v2/pull/345

**Comment by Evert0x** [comment]
Planning to accept escalations and duplicate https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/446, https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/431, https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/537 together

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #446

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [nevillehuang](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/207/#issuecomment-1762745191): accepted
- [jkoppel](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/207/#issuecomment-1762781805): accepted
