### ISSUE TITLE
osmanozdemir1 - `DonationVotingMerkleDistributionBaseStrategy::_distribute()` should have `onlyAfterAllocation` modifier

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#464]
osmanozdemir1

medium

# `DonationVotingMerkleDistributionBaseStrategy::_distribute()` should have `onlyAfterAllocation` modifier
`DonationVotingMerkleDistributionBaseStrategy::_distribute()` function doesn't check if the allocation period is ended or not. Distributions can be started while allocations are continuing.

## Vulnerability Detail
The action flow in this protocol is like this: *registration -&gt; allocation -&gt; distribution.*

Registrations can be done when `onlyActiveRegistration`,  
Allocations can be done when `onlyActiveAllocation`.

Distributions should be done when the allocation is over. This is the case in the QV strategy ([link for the QV strategy](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L441)), and RFP strategy ([link for the RFP strategy](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L421)).

But this check is missing in the DonationVoting strategy and distributions can start even when the allocations are still active.  
[https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L609-L613](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L609C5-L613C33)

```solidity
    function _distribute(address[] memory, bytes memory _data, address _sender)
        internal
        virtual
        override
        onlyPoolManager(_sender) //@audit onlyAfterAllocation is missing
    {
        // ... rest of the code
    }
```

Distributions can be done only once for each recipient and the distribution bitmap gets updated.  
Early distribution during the allocation period will update the bitmap. Any additional allocations for this recipient will not be distributed again since `_hasBeenDistributed()` will return `true` and distribution will revert.

## Impact
Allocations made for the recipient will be lost if the distribution has already been made before the allocation period ends.

## Code Snippet
[https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L609-L613](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L609C5-L613C33)

```solidity
    function _distribute(address[] memory, bytes memory _data, address _sender)
        internal
        virtual
        override
        onlyPoolManager(_sender) //@audit onlyAfterAllocation is missing
    {
        // ... rest of the code
    }
```

## Tool used

Manual Review

## Recommendation
Add `onlyAfterAllocation` modifier

**Comment by osmanozdemir1** [comment]
Escalate

I don't agree with the comment saying this is invalid due to this contract being an abstract. There are multiple abstract contract in this protocol. One of them is the basic [BaseStrategy.sol](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/BaseStrategy.sol), which doesn't implement any logic, doesn't have any modifiers for the [`_distribute`](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/BaseStrategy.sol#L315) function or other internal functions, as the judge's comment above.

However, the [DonationVotingMerkleDistributionBaseStrategy.sol](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol) and the [QVBaseStrategy.sol](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L441) are also abstract contracts but they include most of the logic of these strategies. The protocol performs almost all of the excessive checks in these base contracts.
 
For example `QVBaseStrategy::_distribute()` function is the direct match of the submitted issue above. `QVBaseStrategy.sol` is also an [abstract](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L30) contract but it has [`onlyAfterAllocation`](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L441) modifier in it's `_distribute` function.

Or let's check the `DonationVotingMerkleDistributionBaseStrategy.sol` abstract contract, which is the contract that is submitted in this issue. It performs rigorous checks in multiple functions: [_registerRecipient](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L531), [_allocate](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L640C87-L640C107), [updateDistribution](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L422) and many more checks happen in this contract even though it is abstract.

The logic is implemented in these base abstract contracts throughout the protocol, and an important check is missing in the `DonationVotingMerkleDistributionBaseStrategy::_distribute()` function. The impact of this missing check is obvious: Any distribution made before the allocation period ends will cause loss of funds because it can only be distributed once. 

The contract being abstract should not invalidate the submission. I also want to point out that the other contracts that inherit this base contract also do not include any check for the current issue. 

As a reference, #839, #835, and #261 are validated and rewarded submissions, and all of these also describe incorrect checks in abstract contracts.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I don't agree with the comment saying this is invalid due to this contract being an abstract. There are multiple abstract contract in this protocol. One of them is the basic [BaseStrategy.sol](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/BaseStrategy.sol), which doesn't implement any logic, doesn't have any modifiers for the [`_distribute`](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/BaseStrategy.sol#L315) function or other internal functions, as the judge's comment above.
> 
> However, the [DonationVotingMerkleDistributionBaseStrategy.sol](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol) and the [QVBaseStrategy.sol](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L441) are also abstract contracts but they include most of the logic of these strategies. The protocol performs almost all of the excessive checks in these base contracts.
>  
> For example `QVBaseStrategy::_distribute()` function is the direct match of the submitted issue above. `QVBaseStrategy.sol` is also an [abstract](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L30) contract but it has [`onlyAfterAllocation`](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L441) modifier in it's `_distribute` function.
> 
> Or let's check the `DonationVotingMerkleDistributionBaseStrategy.sol` abstract contract, which is the contract that is submitted in this issue. It performs rigorous checks in multiple functions: [_registerRecipient](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L531), [_allocate](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L640C87-L640C107), [updateDistribution](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L422) and many more checks happen in this contract even though it is abstract.
> 
> The logic is implemented in these base abstract contracts throughout the protocol, and an important check is missing in the `DonationVotingMerkleDistributionBaseStrategy::_distribute()` function. The impact of this missing check is obvious: Any distribution made before the allocation period ends will cause loss of funds because it can only be distributed once. 
> 
> The contract being abstract should not invalidate the submission. I also want to point out that the other contracts that inherit this base contract also do not include any check for the current issue. 
> 
> As a reference, #839, #835, and #261 are validated and rewarded submissions, and all of these also describe incorrect checks in abstract contracts.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
This issue is describing a very similar impact of distribution before allocation to #839, but the root cause is different and due to a missing modifier. In fact this issue has a higher probability of occurring due to the completely missing  `onlyAfterAllocation()` modifier, instead of it being faulty. If #839 is valid, this should be a valid issue as well. 

Perhaps they could be duplicates since impact is very similar? I personally would separate them, but will leave it up to @hrishibhat to decide

**Comment by neeksec** [comment]
Suggest to keep invalid.

`_distribute` don't need onlyAfterAllocation modifier. `_distribute` call `_validateDistribution` to verify the merkle tree data and merkle tree is generated and submitted after allocation period. So `_distribute` won't work if allocation has not ended.

**Comment by osmanozdemir1** [comment]
> Suggest to keep invalid.
> 
> `_distribute` don't need onlyAfterAllocation modifier. `_distribute` call `_validateDistribution` to verify the merkle tree data and merkle tree is generated and submitted after allocation period. So `_distribute` won't work if allocation has not ended.

Yes you're right. I totally missed that and it looks like it's invalid. Thanks

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [osmanozdemir1](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/464/#issuecomment-1762784464): rejected
