### ISSUE TITLE
ace13567 - "Pool Admin" role cannot be assigned to other users due to lack an admin role

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#558]
ace13567

high

# "Pool Admin" role cannot be assigned to other users due to lack an admin role
"Pool Admin" role cannot be assigned to other users due to lack an admin role

## Vulnerability Detail
In a pool, there are two roles: POOL_MANAGER_ROLE and POOL_ADMIN_ROLE. POOL_ADMIN_ROLE serves as the administrator for POOL_MANAGER_ROLE. However, there is no administrative role designated for POOL_ADMIN_ROLE, which means that POOL_ADMIN_ROLE cannot be assigned to other users.

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L429-L449

## Impact
In the pool, there is only one admin user. If this user wishes to exit the project, it is not possible to transfer the admin privileges to a new manager.

## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L429-L449

## Tool used

Manual Review

## Recommendation
Setting POOL_ADMIN_ROLE to also be its own admin. _setRoleAdmin(POOL_ADMIN_ROLE, POOL_ADMIN_ROLE);

**Comment by ace13567** [comment]
Escalate
I think this is at lest a med issue. In all DApps, administrators should not be an EOA but rather a MultiSig wallet or a DAO. If an EOA is designated as the administrator, it would diminish user trust and reduce user engagement with the DApp. Therefore, to gain user trust and enhance user participation, all administrators should be configured as MultiSig wallets or DAOs, as this is a fundamental principle of web3. Typically, contracts are deployed by an EOA, and then the grantRole() and revokeRole() functions are used to establish administrators as MultiSig wallets or DAOs.

In this issue, POOL_ADMIN_ROLE is assigned to msg.sender in _createPool(), and msg.sender is likely to be an EOA. However, POOL_ADMIN_ROLE lacks an admin role, which would prevent granting POOL_ADMIN_ROLE to a MultiSig wallet or DAO. Additionally, it's important to note that POOL_ADMIN_ROLE serves as the admin role for POOL_MANAGER_ROLE, and only a pool admin has the authority to add or remove pool managers. In Allo, pool managers have the capability to perform various operations such as allocate(), distribute(), setMilestones(), withdraw(), reviewRecipients(), and more. To gain user trust and increase willingness to donate, it's better to grant pool admin to a MultiSig wallet or DAO.

Due to the absence of an admin role for POOL_ADMIN_ROLE, the pool admin is unable to grant permissions to a MultiSig wallet or DAO. This could potentially reduce user enthusiasm for making donations.

**Comment by sherlock-admin2** [comment]
> Escalate
> I think this is at lest a med issue. In all DApps, administrators should not be an EOA but rather a MultiSig wallet or a DAO. If an EOA is designated as the administrator, it would diminish user trust and reduce user engagement with the DApp. Therefore, to gain user trust and enhance user participation, all administrators should be configured as MultiSig wallets or DAOs, as this is a fundamental principle of web3. Typically, contracts are deployed by an EOA, and then the grantRole() and revokeRole() functions are used to establish administrators as MultiSig wallets or DAOs.
> 
> In this issue, POOL_ADMIN_ROLE is assigned to msg.sender in _createPool(), and msg.sender is likely to be an EOA. However, POOL_ADMIN_ROLE lacks an admin role, which would prevent granting POOL_ADMIN_ROLE to a MultiSig wallet or DAO. Additionally, it's important to note that POOL_ADMIN_ROLE serves as the admin role for POOL_MANAGER_ROLE, and only a pool admin has the authority to add or remove pool managers. In Allo, pool managers have the capability to perform various operations such as allocate(), distribute(), setMilestones(), withdraw(), reviewRecipients(), and more. To gain user trust and increase willingness to donate, it's better to grant pool admin to a MultiSig wallet or DAO.
> 
> Due to the absence of an admin role for POOL_ADMIN_ROLE, the pool admin is unable to grant permissions to a MultiSig wallet or DAO. This could potentially reduce user enthusiasm for making donations.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
