### ISSUE TITLE
ast3ros - Exploitable Matching Fund Allocation in Donation Voting

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#784]
ast3ros

high

# Exploitable Matching Fund Allocation in Donation Voting

Recipients within the Donation Voting pool can manipulate the system to unfairly garner a larger share of matching funds.

## Vulnerability Detail

In Donation Voting strategies, recipients can accept donations from any address during the allocation period.

                function _allocate(bytes memory _data, address _sender) internal virtual override onlyActiveAllocation { 

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L640

Here's how the strategy operates:

                The amounts sent using allocate are not simply donations, they represent "votes" and the pool amount represents the matching amount. After the allocation happened, the votes are evaluated using an off chain calculation. And based on that calculation the pool amount gets distributed to the recipients.

Donations can either be directly transferred to the recipients  (DonationVotingMerkleDistributionDirectTransferStrategy) or claimed  (DonationVotingMerkleDistributionVaultStrategy) without any associated fees.

A rogue recipient could exploit this by creating multiple addresses and funneling large donations to themselves, thereby inflating their share of the matching pool without any risk.

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol#L45-L74
                
## Impact

The loophole allows any recipient to game the system and secure a disproportionate share of the matching funds, disadvantaging other legitimate recipients.

## Code Snippet

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L640

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol#L45-L74

## Tool used

Manual Review

## Recommendation

Options:

- implementing a whitelist of approved addresses that can participate in the _allocate function.
- impose a donation fee to raise the cost of carrying out such manipulation.

**Comment by thangtranth** [comment]
Escalate

This is the exploitation to gain shares of matching pool and the malicious users can do it risk free. Please help to review.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is the exploitation to gain shares of matching pool and the malicious users can do it risk free. Please help to review.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Sugguest to keep invalid.

The attacker donating to themselves will not affect other participants in the system.

**Comment by neeksec** [comment]
Suggest to keep invalid.

These strategies are to distribute the donated tokens to target recipient. Attacker donating tokens to himself won't affect others.

Similar to #833.

**Comment by thangtranth** [comment]
Hi, in my report I mentioned the target recipient is the malicious user. He can game the system to get more matching funds from the pool.

**Comment by neeksec** [comment]
The target recipient gets the exact amount of tokens others/himself donated to him. And the exact type of tokens, Not the pool token I believe.

**Comment by thelostone-mc** [comment]
In this version, the payouts are set by the pool admin
We'd have off-chain analysis to ensure only donations made from addresses which a passport score greater than X.
This is done off-chain currently and hence is not an issue.

In the future once Gitcoin passport goes onchain -> Allo will have another strategy which directly relies on passport score to ensure we have valid users. Currently this is done off-chain and not in scope

**Comment by thangtranth** [comment]
@neeksec in allocation period, the target recipient receive exact amount of tokens donated to him. However at the distribution phase, the fund in the pool will be distributed based on the those amount (they represent "votes").

@thelostone-mc : I understand that you can have an off chain mechanism to decide which donation to count as vote. Assume it scores addresses correctly, however from theory, "the addresses have passport score greater than X" can collude with the recipients without any risk (since the donation is direct and without fee). We need to assume that they can be adversaries that want to game the system. Unless you can assume that all those donators are honest all the time, which is a big assumption.

**Comment by neeksec** [comment]
The report suggests the following,

> implementing a whitelist of approved addresses that can participate in the _allocate function.
impose a donation fee to raise the cost of carrying out such manipulation.

The first one is already implemented off-chain said by sponsor.
The second one does not completely solve the problem. This can still happen as long as the profits go beyond the cost.

This issue seems unavoidable on-chain and it looks like more of a responsibility in the offchain script to ensure the safety.

**Comment by Evert0x** [comment]
I would say this is an informational issue. The report is pointing out a potential flawed design, but the potential fixes have it's own flaws as well.

It's a fundamental design challenge to the protocol, the current solution is to leverage off chain mechanisms. 

Planning to reject escalation and keep issue state as is

**Comment by thangtranth** [comment]
@neeksec: I recommend implementing a whitelist because from the code, the `allocate` function can be called by anyone. 
Combining with the information from the sponsor about the strategy, it led me to conclude that it is the vulnerability that can be exploited. In the contest period, there was no mention about the whitelist to prevent the issue. I do not try to re-report a solution already implemented by the sponsor. Additionally, I believe that the absence of a complete recommendation shouldn't invalidate the issue.

@Evert0x : Considering the potential consequences of manipulating the votes and getting the additional funds from pool, I am unsure why it is informational. It really discourages reporting issue related to design that can have potential consequences for users.

**Comment by neeksec** [comment]
> In the contest period, there was no mention about the whitelist to prevent the issue.

This is true. 

>  the votes are evaluated using an off chain calculation.

Since this one involves off chain mechanisms which is known during the contest,
I think Watson should draw clear distinction on the responsibilities between on-chain and off-chain code.

I think it is the intended behavior that `allocate` does not have whitelist on-chain. Manager don't know who will donate beforehand. Having the whole gitcoin registrant as whitelist on-chain is meaningless.

Since the recommandations won't fix this on-chain, it made me think that this is not avoidable on-chain and not a responsibility in on-chain code.

**Comment by thangtranth** [comment]
I'm uncertain about the best course of action in situations like this. If I identify a potential vulnerability but there's no mention of any off-chain preventative measures, should I:

- Follow information in Readme (consider the source of truth), report the issue and suggest a solution on-chain?
- Or should I hold off, hoping that the protocol has undisclosed off-chain mechanisms to address the issue? (Fortunately, in this instance, the sponsor reveal there exists a mechanism after the issue was reported.)

**Comment by Evert0x** [comment]
@thangtranth In case you have doubts about the on-chain and off-chain responsibilities you can seek clarification in the public discord channel. 

Planning to reject escalation and keep invalid

**Comment by thangtranth** [comment]
@Evert0x : In this situation, the off-chain script responsibility was already described in public discord and readme (and it **does not have** a whitelist). It is not the case when there is no information about the off-chain responsibilities and I make up how it works. It is when the off-chain system works **properly as described** and the issue exists.

So now you suggest that I ask if the vulnerability is possible in public discord? I think it is unfair to do that.

**Comment by Evert0x** [comment]
@thangtranth but based on the protocol comment it's clear that the off-chain system is mitigating this issue

> We'd have off-chain analysis to ensure only donations made from addresses which a passport score greater than X.
This is done off-chain currently and hence is not an issue.

So that indicates the off-chain responsibility was not described in full detail in public discord and readme.

**Comment by thangtranth** [comment]
@Evert0x : Yes, you can even check the script provided by sponsor. There is no whitelist or passport score there. 

> [Q: Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, input validation expectations, etc)?](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/README.md#q-are-there-any-off-chain-mechanisms-or-off-chain-procedures-for-the-protocol-keeper-bots-input-validation-expectations-etc)
Metadata struct references IPFS
DonationVotingMerkleDistributionBaseMerkle has calculations which happens off-chain based on which a merkle root is generated and uploaded. The pool manager is a trusted role and is expected to use https://github.com/gitcoinco/pluralistic.js

This is the key piece of information for the donation voting strategy, it decides whether to count a donation as voting or not. And it is "missing". 

Invalidating an issue due to a missing information, I think it is unfair to Watsons who try to find vulnerabilities in the contest context.

**Comment by Evert0x** [comment]
> I understand that you can have an off chain mechanism to decide which donation to count as vote.

> This is the key piece of information for the donation voting strategy, it decides whether to count a donation as voting or not. And it is "missing".

You provided the first comment earlier, indicating  that you understood the off chain mechanism related to the donation/vote mechanism

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thangtranth](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/784/#issuecomment-1764018165): rejected
