### ISSUE TITLE
0xHelium - Users funds can get stuck forever inside Allo contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#8]
0xHelium

medium

# Users funds can get stuck forever inside Allo contract

The ```Registry.recoverFunds()``` function allow the ALLO_OWNER role detentor to withdraw any funds balance from allo to the recipient. However Funds can get stuck forever in the contract, if the role detentor account owner loses access to his wallet for whatever reasons.
## Vulnerability Detail

The ```Registry.recoverFunds()``` function allow the ALLO_OWNER role detentor to withdraw any funds balance from allo to the recipient. Due to the way openzeppelin access control works the owner account can not grant ALLO_OWNER role to a new account because owner does not grand himself the ```DEFAULT_ADMIN_ROLE``` from  OZ AccessControl during deployment.

## Impact

Funds can get stuck forever in the contract if owner loses access to his wallet due to any inconvenience: 
-death of the owner,
-wallet compromised,
etc...

Let's see it in live action:

if owner try to grant ALLO_OWNER role to a new account transaction will revert with the following error:
```solidity
"AccessControl: account 0x5b38da6a701c568545dcfcb03fcb875f56beddc4 is missing role 0x0000000000000000000000000000000000000000000000000000000000000000", (which is the DEFAULT_ADMIN_ROLE).
```

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.18;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";

contract Proof is AccessControl {
   // @audit: this contract won't allow owner to grant any role to a new account
  // in case owner is sick for example and want to grant role to a new account for precaution
// he can't. Same thing if he loses access to his wallet.
    bytes32 public constant ALLO_OWNER = keccak256("ALLO_OWNER");
    constructor() {
       _grantRole(ALLO_OWNER, _msgSender());
    }
}
```

## Code Snippet

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Registry.sol#L384-L389

## Tool used

Manual Review

## Recommendation
owner should grant himself Oz DEFAULT_ADMIN_ROLE at deployment, so he can get full access control and grant role to new accounts if the current one is compromised

**Comment by quentin-abei** [comment]
Escalate
Judge comment suggest he just looked at the resume and did not look further in my issue:
In Vulnerability details i explain:
- The Registry.recoverFunds() function allow the ALLO_OWNER role detentor to withdraw any funds balance from allo to the recipient. Due to the way openzeppelin access control works the owner account can not grant ALLO_OWNER role to a new account because owner does not grand himself the DEFAULT_ADMIN_ROLE from OZ AccessControl during deployment.

So the root problem is owner can not grant role to new account as expected because he do not have the default admin role, and my provided PoC explain this well, if you copy PoC and paste it in remix you will see that owner can not grant role to a new account. To be able to do so dev should grant owner account standar Openzeppelin DEFAULT_ADMIN_ROLE at deployment.
Because of this i consider this issue to be a valid high since the intended functionality can not be achieved because of an improper external library integration.

**Comment by sherlock-admin2** [comment]
> Escalate
> Judge comment suggest he just looked at the resume and did not look further in my issue:
> In Vulnerability details i explain:
> - The Registry.recoverFunds() function allow the ALLO_OWNER role detentor to withdraw any funds balance from allo to the recipient. Due to the way openzeppelin access control works the owner account can not grant ALLO_OWNER role to a new account because owner does not grand himself the DEFAULT_ADMIN_ROLE from OZ AccessControl during deployment.
> 
> So the root problem is owner can not grant role to new account as expected because he do not have the default admin role, and my provided PoC explain this well, if you copy PoC and paste it in remix you will see that owner can not grant role to a new account. To be able to do so dev should grant owner account standar Openzeppelin DEFAULT_ADMIN_ROLE at deployment.
> Because of this i consider this issue to be a valid high since the intended functionality can not be achieved because of an improper external library integration.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
